import streamlit as st
import pandas as pd
import yfinance as yf

st.set_page_config(page_title="Smart Hedge AI Terminal", layout="wide")

st.title("Smart Hedge AI Terminal V4")

# Major F&O Stocks
symbols = {

"NIFTY":"^NSEI",

"RELIANCE":"RELIANCE.NS",
"HDFCBANK":"HDFCBANK.NS",
"ICICIBANK":"ICICIBANK.NS",
"TCS":"TCS.NS",
"INFY":"INFY.NS",
"SBIN":"SBIN.NS",
"AXISBANK":"AXISBANK.NS",
"KOTAKBANK":"KOTAKBANK.NS",
"ITC":"ITC.NS",
"LT":"LT.NS",
"BAJFINANCE":"BAJFINANCE.NS",
"BAJAJFINSV":"BAJAJFINSV.NS",
"HINDUNILVR":"HINDUNILVR.NS",
"ASIANPAINT":"ASIANPAINT.NS",
"MARUTI":"MARUTI.NS",
"ULTRACEMCO":"ULTRACEMCO.NS",
"TITAN":"TITAN.NS",
"NTPC":"NTPC.NS",
"POWERGRID":"POWERGRID.NS",
"ONGC":"ONGC.NS",
"COALINDIA":"COALINDIA.NS",
"ADANIENT":"ADANIENT.NS",
"ADANIPORTS":"ADANIPORTS.NS",
"JSWSTEEL":"JSWSTEEL.NS",
"TATASTEEL":"TATASTEEL.NS",
"HCLTECH":"HCLTECH.NS",
"TECHM":"TECHM.NS",
"WIPRO":"WIPRO.NS",
"BHARTIARTL":"BHARTIARTL.NS",
"DRREDDY":"DRREDDY.NS",
"SUNPHARMA":"SUNPHARMA.N
